# This is a config for E2B sandbox template.
# You can use template ID (oo7hag798omak4bdwxic) or template name (vibe-nextjs-first) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-first") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-first") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-first')

team_id = "4dd3acdc-0728-4635-beb3-41dc1b43c5e7"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-first"
template_id = "oo7hag798omak4bdwxic"
